# Service creates access to associated pod for all other pods within node cluster 
apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    # selector targets label of associated deployment
    component: web
  ports:
    # service port
    - port: 3000
    # container/pod port
      targetPort: 3000