apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template: 
    metadata:
      labels: 
        component: postgres
    spec:
      # allocate storage claim to postgres template
      volumes:
        - name: postgres-storage
          persistentVolumeClaim: 
            claimName: database-persistent-volume-claim 
      containers:
        - name: postgres
          # public docker repository
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts: 
            # maps to volume name. Allocate volume to container!
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            # overwrite default password!
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD