apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template: 
    metadata:
      labels: 
        component: server
    spec:
      containers:
        - name: server
          image: maxbl/multi-server
          ports:
            # port of each container/pod
            - containerPort: 5000
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              # env values of string habve to be provided as string!
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom: 
                # values from imperativ command "kubectl crteate secret ..."
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD